### ISSUE TITLE
ITX mainboard power connectors not in BOM

### ISSUE THREAD

**Issue by bingzap2** [warmech/lisa-hardware#2]
Great work on this project!  It looks so good I can't resist building it.  I see one issue though that is not in the assembly instructions and is missing on the BOM.

The PCB has a location for the 24 pin ATX connector.  From the picture it looks like you desoldered the ATX connector on the Pico ATX PSU and moved/added a connector on the back and (I assume) to the PCB.  The connector doesn't seem to be in the BOM but the instructions mention "Loosely insert the Pico ATX PSU into its connector".  What did you do here?  What part(s) did you use?  I know there are many ways to get the job done here but wondered what you did.

Thanks,

Dave

**Comment by warmech** [comment]
I apologize, as I just saw this. I hadn't checked this repo until yesterday when I needed to add some things, so I haven't paid close attention to it in a bit.

With respect to the Pico ATX PSU, the one I used would not have fit as it was manufactured. Instead, I had to de-solder the ATX connector from the front of the Pico PCB and re-install it on the reverse side, being careful to ensure that the orientation of the connector lined up with the correct pinout. This may not be necessary with other Pico PSUs but it was with mine, unfortunately.
